#!/usr/bin/python3.6

import requests
import sys

print("""
------------------------------------------------------
BruteD \033[1;33mv0.15\033[m
By \033[1;36mFsociety800\033[m
Editado por \033[1;36mAlcaTech\033[m


8888888b.  d8b         888      8888888b.           
888  "Y88b Y8P         888      888   Y88b          
888    888             888      888    888          
888    888 888 888d888 88888b.  888   d88P 888  888 
888    888 888 888P"   888 "88b 8888888P"  888  888 
888    888 888 888     888  888 888        888  888 
888  .d88P 888 888     888 d88P 888        Y88b 888 
8888888P"  888 888     88888P"  888         "Y88888 
                                                888 
                                           Y8b d88P 
                                            "Y88P"


------------------------------------------------------""")

if 'http://' in sys.argv[1] or 'https://' in sys.argv[0]:

	if len(sys.argv) == 3:
		url = sys.argv[1]
		worddir = sys.argv[2]
		if worddir == "default":
			worddir = "data/data/com.termux/files/home/Dirbpy/wordlist.txt"
		wordopen = open(worddir,"r")
		wordline = wordopen.readlines()
		wordlist = ['-']

		for line in wordline:
			line = line.rstrip()
			wordlist.append(line)
		real = len(wordlist); unreal = real - 1
		print("""
GENERATED WORDS: \033[1;33m{}\033[m

-------------------\033[1;32mScanning iniciado\033[m-------------------\n""".format(unreal))
		wordlistqnt = len(wordlist)
		linha = 0; status = 'running'
		while 'running' in status:
			linha += 1
			codes = [200,403,404]
			if linha < wordlistqnt:
				target = '{}{}'.format(url,wordlist[linha])
				request = requests.post(target)
				code = request.status_code
				if code == codes[0]:
					print("+ [\033[1;32m200\033[m] {}".format(target))
				elif code == codes[1]:
					print("+ [\033[1;33m403\033[m] {}".format(target))
				elif code == codes[2]:
					print("- [\033[1;31m404\033[m] {}".format(target))
				elif code not in codes:
					print("+ [\033[1;34m{}\033[m] {} \033[1;31mUnknown\033[m".format(code,target))
				else:
					a = 0
			else:
				status = 'stopping'


		print("\n------------------\033[1;32mScanning Finalizado\033[m-------------------\n""".format(unreal))
	else:
		print("""
- [\033[1;31mERROR\033[m] Parâmetros incorretos.

Digite: \033[1;32mDirbpy [url] [wordlist / default.]\033[m \n
------------------------------------------------------\n""")

else:
	print("""
- [\033[1;31mERROR\033[m] Parâmetros incorretos.

Digite: \033[1;32mDirbpy [url] [wordlist / default.]\033[m \n
------------------------------------------------------\n""".format(sys.argv[1]))

